import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";

const momCake = localFont({
  src: "../public/fonts/MomCake.otf",
  variable: "--font-mom-cake",
});

const lemonMilk = localFont({
  src: "../public/fonts/LemonMilk.otf",
  variable: "--font-lemon-milk",
});
const metropolis = localFont({
  src: "../public/fonts/Metropolis.otf",
  variable: "--font-metropolis",
});

export const metadata: Metadata = {
  title: "LazyPress",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${momCake.variable} ${lemonMilk.variable} ${metropolis.variable} flex min-h-svh flex-col antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
